/**
 * Client side of the operation contract.
 *
 * Maps every contract operation to the client method that implements it. The
 * map is total over `OperationName`, so adding a contract entry without a
 * client method is a compile error; the conformance test additionally checks
 * that each referenced method actually exists at runtime.
 */

import type { OperationName } from '@automaker/types';

export interface ClientMethodRef {
  /** Namespace on the `HttpApiClient`, e.g. 'features'. */
  namespace: string;
  /** Method name within the namespace, e.g. 'getAll'. */
  method: string;
}

export const CLIENT_OPERATION_METHODS: Record<OperationName, ClientMethodRef> = {
  'features.list': { namespace: 'features', method: 'getAll' },
  'features.listPost': { namespace: 'features', method: 'getAll' },
  'features.get': { namespace: 'features', method: 'get' },
  'features.create': { namespace: 'features', method: 'create' },
  'features.update': { namespace: 'features', method: 'update' },
  'features.bulkUpdate': { namespace: 'features', method: 'bulkUpdate' },
  'features.bulkDelete': { namespace: 'features', method: 'bulkDelete' },
  'features.delete': { namespace: 'features', method: 'delete' },
  'features.getAgentOutput': { namespace: 'features', method: 'getAgentOutput' },
  'features.rawOutput': { namespace: 'features', method: 'getRawOutput' },
  'features.generateTitle': { namespace: 'features', method: 'generateTitle' },
  'features.export': { namespace: 'features', method: 'export' },
  'features.import': { namespace: 'features', method: 'import' },
  'features.checkConflicts': { namespace: 'features', method: 'checkConflicts' },
  'features.getOrphaned': { namespace: 'features', method: 'getOrphaned' },
  'features.resolveOrphaned': { namespace: 'features', method: 'resolveOrphaned' },
  'features.bulkResolveOrphaned': { namespace: 'features', method: 'bulkResolveOrphaned' },
  'autoMode.start': { namespace: 'autoMode', method: 'start' },
  'autoMode.stop': { namespace: 'autoMode', method: 'stop' },
  'autoMode.stopFeature': { namespace: 'autoMode', method: 'stopFeature' },
  'autoMode.status': { namespace: 'autoMode', method: 'status' },
  'autoMode.runFeature': { namespace: 'autoMode', method: 'runFeature' },
  'autoMode.verifyFeature': { namespace: 'autoMode', method: 'verifyFeature' },
  'autoMode.resumeFeature': { namespace: 'autoMode', method: 'resumeFeature' },
  'autoMode.contextExists': { namespace: 'autoMode', method: 'contextExists' },
  'autoMode.analyzeProject': { namespace: 'autoMode', method: 'analyzeProject' },
  'autoMode.followUpFeature': { namespace: 'autoMode', method: 'followUpFeature' },
  'autoMode.commitFeature': { namespace: 'autoMode', method: 'commitFeature' },
  'autoMode.approvePlan': { namespace: 'autoMode', method: 'approvePlan' },
  'autoMode.resumeInterrupted': { namespace: 'autoMode', method: 'resumeInterrupted' },
  'autoMode.reconcile': { namespace: 'autoMode', method: 'reconcile' },
  'runningAgents.getAll': { namespace: 'runningAgents', method: 'getAll' },
  'worktree.info': { namespace: 'worktree', method: 'getInfo' },
  'worktree.status': { namespace: 'worktree', method: 'getStatus' },
  'worktree.list': { namespace: 'worktree', method: 'list' },
  'worktree.diffs': { namespace: 'worktree', method: 'getDiffs' },
  'worktree.fileDiff': { namespace: 'worktree', method: 'getFileDiff' },
  'worktree.merge': { namespace: 'worktree', method: 'mergeFeature' },
  'worktree.create': { namespace: 'worktree', method: 'create' },
  'worktree.delete': { namespace: 'worktree', method: 'delete' },
  'worktree.openInEditor': { namespace: 'worktree', method: 'openInEditor' },
  'worktree.openInTerminal': { namespace: 'worktree', method: 'openInTerminal' },
  'worktree.getDefaultEditor': { namespace: 'worktree', method: 'getDefaultEditor' },
  'worktree.getAvailableEditors': { namespace: 'worktree', method: 'getAvailableEditors' },
  'worktree.refreshEditors': { namespace: 'worktree', method: 'refreshEditors' },
  'worktree.getAvailableTerminals': { namespace: 'worktree', method: 'getAvailableTerminals' },
  'worktree.getDefaultTerminal': { namespace: 'worktree', method: 'getDefaultTerminal' },
  'worktree.refreshTerminals': { namespace: 'worktree', method: 'refreshTerminals' },
  'worktree.openInExternalTerminal': {
    namespace: 'worktree',
    method: 'openInExternalTerminal',
  },
  'worktree.initGit': { namespace: 'worktree', method: 'initGit' },
  'worktree.migrate': { namespace: 'worktree', method: 'migrate' },
  'worktree.startDev': { namespace: 'worktree', method: 'startDevServer' },
  'worktree.stopDev': { namespace: 'worktree', method: 'stopDevServer' },
  'worktree.listDevServers': { namespace: 'worktree', method: 'listDevServers' },
  'worktree.getDevServerLogs': { namespace: 'worktree', method: 'getDevServerLogs' },
  'worktree.startTests': { namespace: 'worktree', method: 'startTests' },
  'worktree.stopTests': { namespace: 'worktree', method: 'stopTests' },
  'worktree.getTestLogs': { namespace: 'worktree', method: 'getTestLogs' },
  'worktree.getInitScript': { namespace: 'worktree', method: 'getInitScript' },
  'worktree.setInitScript': { namespace: 'worktree', method: 'setInitScript' },
  'worktree.deleteInitScript': { namespace: 'worktree', method: 'deleteInitScript' },
  'worktree.runInitScript': { namespace: 'worktree', method: 'runInitScript' },
  'worktree.createPR': { namespace: 'worktree', method: 'createPR' },
  'worktree.getPRInfo': { namespace: 'worktree', method: 'getPRInfo' },
  'worktree.updatePRNumber': { namespace: 'worktree', method: 'updatePRNumber' },
  'worktree.commit': { namespace: 'worktree', method: 'commit' },
  'worktree.generateCommitMessage': { namespace: 'worktree', method: 'generateCommitMessage' },
  'worktree.push': { namespace: 'worktree', method: 'push' },
  'worktree.pull': { namespace: 'worktree', method: 'pull' },
  'worktree.sync': { namespace: 'worktree', method: 'sync' },
  'worktree.setTracking': { namespace: 'worktree', method: 'setTracking' },
  'worktree.checkoutBranch': { namespace: 'worktree', method: 'checkoutBranch' },
  'worktree.checkChanges': { namespace: 'worktree', method: 'checkChanges' },
  'worktree.listBranches': { namespace: 'worktree', method: 'listBranches' },
  'worktree.switchBranch': { namespace: 'worktree', method: 'switchBranch' },
  'worktree.discardChanges': { namespace: 'worktree', method: 'discardChanges' },
  'worktree.listRemotes': { namespace: 'worktree', method: 'listRemotes' },
  'worktree.addRemote': { namespace: 'worktree', method: 'addRemote' },
  'worktree.getCommitLog': { namespace: 'worktree', method: 'getCommitLog' },
  'worktree.stashPush': { namespace: 'worktree', method: 'stashPush' },
  'worktree.stashList': { namespace: 'worktree', method: 'stashList' },
  'worktree.stashApply': { namespace: 'worktree', method: 'stashApply' },
  'worktree.stashDrop': { namespace: 'worktree', method: 'stashDrop' },
  'worktree.cherryPick': { namespace: 'worktree', method: 'cherryPick' },
  'worktree.generatePRDescription': {
    namespace: 'worktree',
    method: 'generatePRDescription',
  },
  'worktree.getBranchCommitLog': { namespace: 'worktree', method: 'getBranchCommitLog' },
  'worktree.rebase': { namespace: 'worktree', method: 'rebase' },
  'worktree.abortOperation': { namespace: 'worktree', method: 'abortOperation' },
  'worktree.continueOperation': { namespace: 'worktree', method: 'continueOperation' },
  'worktree.stageFiles': { namespace: 'worktree', method: 'stageFiles' },
  'settings.getStatus': { namespace: 'settings', method: 'getStatus' },
  'settings.getGlobal': { namespace: 'settings', method: 'getGlobal' },
  'settings.updateGlobal': { namespace: 'settings', method: 'updateGlobal' },
  'settings.getCredentials': { namespace: 'settings', method: 'getCredentials' },
  'settings.updateCredentials': { namespace: 'settings', method: 'updateCredentials' },
  'settings.getProject': { namespace: 'settings', method: 'getProject' },
  'settings.updateProject': { namespace: 'settings', method: 'updateProject' },
  'settings.migrate': { namespace: 'settings', method: 'migrate' },
  'settings.discoverAgents': { namespace: 'settings', method: 'discoverAgents' },
  'projects.getOverview': { namespace: 'projects', method: 'getOverview' },
  'context.describeImage': { namespace: 'context', method: 'describeImage' },
  'context.describeFile': { namespace: 'context', method: 'describeFile' },
  'specRegeneration.create': { namespace: 'specRegeneration', method: 'create' },
  'specRegeneration.generate': { namespace: 'specRegeneration', method: 'generate' },
  'specRegeneration.generateFeatures': {
    namespace: 'specRegeneration',
    method: 'generateFeatures',
  },
  'specRegeneration.sync': { namespace: 'specRegeneration', method: 'sync' },
  'specRegeneration.stop': { namespace: 'specRegeneration', method: 'stop' },
  'specRegeneration.status': { namespace: 'specRegeneration', method: 'status' },
  'backlogPlan.generate': { namespace: 'backlogPlan', method: 'generate' },
  'backlogPlan.stop': { namespace: 'backlogPlan', method: 'stop' },
  'backlogPlan.status': { namespace: 'backlogPlan', method: 'status' },
  'backlogPlan.apply': { namespace: 'backlogPlan', method: 'apply' },
  'backlogPlan.clear': { namespace: 'backlogPlan', method: 'clear' },
  'ideation.sessionStart': { namespace: 'ideation', method: 'startSession' },
  'ideation.sessionMessage': { namespace: 'ideation', method: 'sendMessage' },
  'ideation.sessionStop': { namespace: 'ideation', method: 'stopSession' },
  'ideation.sessionGet': { namespace: 'ideation', method: 'getSession' },
  'ideation.ideasList': { namespace: 'ideation', method: 'listIdeas' },
  'ideation.ideasCreate': { namespace: 'ideation', method: 'createIdea' },
  'ideation.ideasGet': { namespace: 'ideation', method: 'getIdea' },
  'ideation.ideasUpdate': { namespace: 'ideation', method: 'updateIdea' },
  'ideation.ideasDelete': { namespace: 'ideation', method: 'deleteIdea' },
  'ideation.analyze': { namespace: 'ideation', method: 'analyzeProject' },
  'ideation.analysis': { namespace: 'ideation', method: 'getAnalysis' },
  'ideation.convert': { namespace: 'ideation', method: 'convertToFeature' },
  'ideation.addSuggestion': { namespace: 'ideation', method: 'addSuggestionToBoard' },
  'ideation.prompts': { namespace: 'ideation', method: 'getPrompts' },
  'ideation.promptsByCategory': { namespace: 'ideation', method: 'getPromptsByCategory' },
  'ideation.suggestionsGenerate': { namespace: 'ideation', method: 'generateSuggestions' },
  'github.checkRemote': { namespace: 'github', method: 'checkRemote' },
  'github.listIssues': { namespace: 'github', method: 'listIssues' },
  'github.listPRs': { namespace: 'github', method: 'listPRs' },
  'github.getIssueComments': { namespace: 'github', method: 'getIssueComments' },
  'github.getPRReviewComments': { namespace: 'github', method: 'getPRReviewComments' },
  'github.resolveReviewThread': { namespace: 'github', method: 'resolveReviewThread' },
  'github.validateIssue': { namespace: 'github', method: 'validateIssue' },
  'github.getValidationStatus': { namespace: 'github', method: 'getValidationStatus' },
  'github.stopValidation': { namespace: 'github', method: 'stopValidation' },
  'github.getValidations': { namespace: 'github', method: 'getValidations' },
  'github.deleteValidation': { namespace: 'github', method: 'deleteValidation' },
  'github.markValidationViewed': { namespace: 'github', method: 'markValidationViewed' },
  'git.diffs': { namespace: 'git', method: 'getDiffs' },
  'git.fileDiff': { namespace: 'git', method: 'getFileDiff' },
  'git.stageFiles': { namespace: 'git', method: 'stageFiles' },
  'git.details': { namespace: 'git', method: 'getDetails' },
  'git.enhancedStatus': { namespace: 'git', method: 'getEnhancedStatus' },
  'templates.clone': { namespace: 'templates', method: 'clone' },
  'models.available': { namespace: 'model', method: 'getAvailable' },
  'models.providers': { namespace: 'model', method: 'checkProviders' },
  'fs.read': { namespace: 'fs', method: 'readFile' },
  'fs.write': { namespace: 'fs', method: 'writeFile' },
  'fs.mkdir': { namespace: 'fs', method: 'mkdir' },
  'fs.readdir': { namespace: 'fs', method: 'readdir' },
  'fs.exists': { namespace: 'fs', method: 'exists' },
  'fs.stat': { namespace: 'fs', method: 'stat' },
  'fs.delete': { namespace: 'fs', method: 'deleteFile' },
  'fs.validatePath': { namespace: 'fs', method: 'validatePath' },
  'fs.resolveDirectory': { namespace: 'fs', method: 'resolveDirectory' },
  'fs.saveImage': { namespace: 'fs', method: 'saveImageToTemp' },
  'fs.browse': { namespace: 'fs', method: 'browse' },
  'fs.image': { namespace: 'fs', method: 'getImageUrl' },
  'fs.saveBoardBackground': { namespace: 'fs', method: 'saveBoardBackground' },
  'fs.deleteBoardBackground': { namespace: 'fs', method: 'deleteBoardBackground' },
  'fs.browseProjectFiles': { namespace: 'fs', method: 'browseProjectFiles' },
  'fs.copy': { namespace: 'fs', method: 'copyItem' },
  'fs.move': { namespace: 'fs', method: 'moveItem' },
  'fs.download': { namespace: 'fs', method: 'downloadItem' },
  'terminal.status': { namespace: 'terminal', method: 'status' },
  'terminal.auth': { namespace: 'terminal', method: 'auth' },
  'terminal.logout': { namespace: 'terminal', method: 'logout' },
  'terminal.sessions': { namespace: 'terminal', method: 'listSessions' },
  'terminal.createSession': { namespace: 'terminal', method: 'createSession' },
  'terminal.deleteSession': { namespace: 'terminal', method: 'deleteSession' },
  'terminal.resizeSession': { namespace: 'terminal', method: 'resizeSession' },
  'terminal.getSettings': { namespace: 'terminal', method: 'getSettings' },
  'terminal.updateSettings': { namespace: 'terminal', method: 'updateSettings' },
  'workspace.config': { namespace: 'workspace', method: 'getConfig' },
  'workspace.directories': { namespace: 'workspace', method: 'getDirectories' },
  'mcp.testServer': { namespace: 'mcp', method: 'testServer' },
  'mcp.listTools': { namespace: 'mcp', method: 'listTools' },
};
